[pipe]
name = "machine01"
source = { path = "nfs://mnt/machine01", size = "25GB" }
destination =  {
	path = "nokura://mybucket/",
	secrets-file = "~/.akyrt/secrets/nokura-secret.json"
}
spillway = { path = "/usr/akyrt/machine01/", size = "10TB" }
threads = { worker = 1, codec = 2 }
encodings = [
	{ 
		extension = "*",
		action = "compress",
		compress = "zstd",
		level = 3
	},
	{ 
		extension = ".bmp",
		action = "transcode",
		format = "jxl",
		colorspace = "gray",
		quality = 100,
		effort = 3
	},
	{
		extension = ".jpg",
		action = "transcode",
		format = "jxl",
		colorspace = "gray",
		quality = 100,
		effort = 3
	}
]